import type { DemoCopy } from "./types";

export const DEMO_COPY: Record<"zh" | "en", DemoCopy> = {
  zh: {
    backToCaseStudy: "返回案例",
    tryDemo: "体验 MonoLOG",
    demoHint: "轻量 Web 演示 · 对话、待办与计时",
    today: "今日",
    data: "数据",
    categories: "分类管理",
    placeholder: "写点什么…",
    taskPlaceholder: "在做什么？",
    inviteAi: "添加 AI 朋友",
    search: "搜索",
    send: "发送",
    countdown: "倒",
    stopwatch: "正",
    min: "min",
    demoBadge: "Web Demo",
    menuPin: "置底",
    menuUnpin: "取消置底",
    menuEdit: "编辑",
    menuToTodo: "转为待办",
    menuToNote: "转为普通笔记",
    menuDelete: "删除",
    editPrompt: "编辑内容",
    periodWeek: "周",
    periodMonth: "月",
    periodYear: "年",
    dataToday: "今天",
    dataPrev: "上一段",
    dataNext: "下一段",
  },
  en: {
    backToCaseStudy: "Back to case study",
    tryDemo: "Try MonoLOG",
    demoHint: "Lightweight web demo · chat, todos & timer",
    today: "Today",
    data: "Data",
    categories: "Categories",
    placeholder: "Write something…",
    taskPlaceholder: "What are you doing?",
    inviteAi: "Add AI friend",
    search: "Search",
    send: "Send",
    countdown: "CD",
    stopwatch: "SW",
    min: "min",
    demoBadge: "Web Demo",
    menuPin: "Pin to bottom",
    menuUnpin: "Unpin",
    menuEdit: "Edit",
    menuToTodo: "Convert to to-do",
    menuToNote: "Convert to note",
    menuDelete: "Delete",
    editPrompt: "Edit text",
    periodWeek: "W",
    periodMonth: "M",
    periodYear: "Y",
    dataToday: "Today",
    dataPrev: "Previous",
    dataNext: "Next",
  },
};
